[project]
name = "cve-acl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiomysql>=0.3.2",
    "loguru>=0.7.3",
    "httpx>=0.24.0",
    "fastapi[standard]>=0.109.0",
    "uvicorn>=0.27.0",
    "polars>=1.36.0",
    "python-dotenv>=1.0.0",
    "agno>=2.4.3",
    "openai>=2.15.0",
    "fastmcp>=3.0.0b1",
    "ddgs>=9.10.0",
    "sqlalchemy>=2.0.46",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "notebook>=7.5.0",
]

[[tool.uv.index]]
url = "https://pypi.org/simple"
default = true
