import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Button, Card, Drawer, Form, Input, Modal, Popconfirm, Space, Switch, Table, Tag, message } from 'antd'
import { DeleteOutlined, HistoryOutlined, PlayCircleOutlined, PlusOutlined } from '@ant-design/icons'
import { PageHeader } from '@/shared/ui/PageHeader'
import { createSchedule, listRuns, listSchedules, remove, setEnabled, trigger } from './api'
import type { Schedule, ScheduleRun } from './types'
import { compactId, formatDate } from '@/shared/lib/format'

export function SchedulerPage() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ['schedules'], queryFn: listSchedules }); const [createOpen, setCreateOpen] = useState(false); const [runSchedule, setRunSchedule] = useState<Schedule | null>(null); const runs = useQuery({ queryKey: ['schedules', runSchedule?.id, 'runs'], queryFn: () => listRuns(runSchedule!.id), enabled: Boolean(runSchedule) }); const refresh = () => client.invalidateQueries({ queryKey: ['schedules'] })
  return <main className="page"><PageHeader title="Scheduler" description="管理 AgentOS cron 任务与执行历史" actions={<Button type="primary" icon={<PlusOutlined />} onClick={() => setCreateOpen(true)}>创建计划</Button>} /><Card className="workbench-card"><Table<Schedule> rowKey="id" dataSource={query.data ?? []} loading={query.isLoading} columns={[{ title: 'Name', dataIndex: 'name' }, { title: 'Endpoint', dataIndex: 'endpoint', ellipsis: true }, { title: 'Cron', dataIndex: 'cron_expr', render: (v) => <code>{v}</code> }, { title: 'Timezone', dataIndex: 'timezone' }, { title: 'Enabled', dataIndex: 'enabled', render: (value, row) => <Switch checked={value} onChange={async (enabled) => { await setEnabled(row.id, enabled); await refresh() }} /> }, { title: 'Actions', render: (_, row) => <Space><Button icon={<PlayCircleOutlined />} onClick={async () => { await trigger(row.id); message.success('任务已触发') }} /><Button icon={<HistoryOutlined />} onClick={() => setRunSchedule(row)} /><Popconfirm title="删除该计划？" onConfirm={async () => { await remove(row.id); await refresh() }}><Button danger icon={<DeleteOutlined />} /></Popconfirm></Space> }]} /></Card>
    <Modal open={createOpen} footer={null} onCancel={() => setCreateOpen(false)} title="创建计划"><Form layout="vertical" initialValues={{ cron_expr: '0 2 * * *', timezone: 'UTC', payload: '{}' }} onFinish={async (values: { name: string; description?: string; endpoint: string; cron_expr: string; timezone: string; payload: string }) => { await createSchedule({ ...values, payload: JSON.parse(values.payload) }); setCreateOpen(false); await refresh() }}><Form.Item name="name" label="名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="endpoint" label="AgentOS endpoint" rules={[{ required: true }]}><Input placeholder="/agents/security-agent/runs" /></Form.Item><Form.Item name="cron_expr" label="Cron"><Input /></Form.Item><Form.Item name="timezone" label="Timezone"><Input /></Form.Item><Form.Item name="payload" label="Payload JSON"><Input.TextArea rows={5} /></Form.Item><Button type="primary" htmlType="submit">创建</Button></Form></Modal>
    <Drawer width={680} open={Boolean(runSchedule)} onClose={() => setRunSchedule(null)} title={`${runSchedule?.name ?? ''} runs`}><Table<ScheduleRun> rowKey="id" dataSource={runs.data ?? []} loading={runs.isLoading} columns={[{ title: 'Run', dataIndex: 'run_id', render: compactId }, { title: 'Status', dataIndex: 'status', render: (v) => <Tag>{v}</Tag> }, { title: 'Triggered', dataIndex: 'triggered_at', render: formatDate }, { title: 'Error', dataIndex: 'error', ellipsis: true }]} /></Drawer>
  </main>
}
