import secrets
import time
import tomllib
from typing import Any

import tomli_w
from psycopg import sql

from api.services.runtime_paths import CONFIG_DIR
from api.services.postgres_store import mcp_schema, postgres_connect, postgres_label

SERVICE_IDS = ("playbook", "basic")
MCP_DATA_DIR = CONFIG_DIR / "mcp"
MCP_CONFIG_FILE = MCP_DATA_DIR / "mcp_config.toml"
MCP_TOKENS_TABLE = "mcp_tokens"
MCP_TOKENS_DB = postgres_label(mcp_schema(), MCP_TOKENS_TABLE)


def _tokens_table() -> sql.Identifier:
    return sql.Identifier(mcp_schema(), MCP_TOKENS_TABLE)


def _ensure_data_dir() -> None:
    MCP_DATA_DIR.mkdir(parents=True, exist_ok=True)


def _default_config() -> dict[str, Any]:
    return {
        "mcp": {service_id: True for service_id in SERVICE_IDS},
        "mcp_servers": [],
    }


def normalize_mcp_servers(entries: Any) -> list[dict[str, Any]]:
    if not isinstance(entries, list):
        return []
    normalized: list[dict[str, Any]] = []
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        name = str(entry.get("name") or "").strip()
        if not name:
            continue
        manifest = entry.get("manifest")
        if not isinstance(manifest, dict):
            manifest = {}
        normalized.append(
            {
                "name": name,
                "description": str(entry.get("description") or "").strip(),
                "kind": str(entry.get("kind") or "unknown").strip(),
                "enabled": bool(entry.get("enabled", True)),
                "manifest": manifest,
            }
        )
    return normalized


def read_mcp_config() -> dict[str, Any]:
    _ensure_data_dir()
    if not MCP_CONFIG_FILE.exists():
        return _default_config()

    try:
        with MCP_CONFIG_FILE.open("rb") as f:
            data = tomllib.load(f)
    except Exception:
        return _default_config()

    if "mcp" not in data or not isinstance(data["mcp"], dict):
        data["mcp"] = {}
    if "mcp_servers" not in data or not isinstance(data["mcp_servers"], list):
        data["mcp_servers"] = []
    return data


def write_mcp_config(data: dict[str, Any]) -> None:
    _ensure_data_dir()
    mcp_cfg = data.setdefault("mcp", {})
    if not isinstance(mcp_cfg, dict):
        data["mcp"] = {}
    data["mcp_servers"] = normalize_mcp_servers(data.get("mcp_servers", []))
    with MCP_CONFIG_FILE.open("wb") as f:
        tomli_w.dump(data, f)


def services_from_config(data: dict[str, Any] | None = None) -> dict[str, bool]:
    cfg = read_mcp_config() if data is None else data
    raw_mcp_cfg = cfg.get("mcp")
    mcp_cfg: dict[str, Any] = raw_mcp_cfg if isinstance(raw_mcp_cfg, dict) else {}
    return {
        service_id: bool(mcp_cfg.get(service_id, True)) for service_id in SERVICE_IDS
    }


def enabled_service_ids() -> set[str]:
    return {
        service_id for service_id, enabled in services_from_config().items() if enabled
    }


def init_mcp_postgres_tables() -> None:
    with postgres_connect() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(
                    sql.Identifier(mcp_schema())
                )
            )
            cursor.execute(
                sql.SQL(
                    """
                CREATE TABLE IF NOT EXISTS {} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL,
                    token TEXT NOT NULL UNIQUE,
                    created_at BIGINT NOT NULL,
                    expires_at BIGINT NOT NULL
                )
                """
                ).format(_tokens_table())
            )


def init_mcp_mysql_tables() -> None:
    init_mcp_postgres_tables()


def init_tokens_db() -> None:
    init_mcp_postgres_tables()


def list_tokens() -> list[dict[str, Any]]:
    init_tokens_db()
    with postgres_connect() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                sql.SQL(
                    """
                SELECT id, name, token, created_at, expires_at
                FROM {}
                ORDER BY created_at DESC
                """
                ).format(_tokens_table())
            )
            return list(cursor.fetchall())


def insert_token(name: str, expires_in: int, token: str | None = None) -> str:
    init_tokens_db()
    now = int(time.time())
    token_value = token or secrets.token_urlsafe(32)
    expires_at = 0 if expires_in == 0 else now + expires_in
    with postgres_connect() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                sql.SQL(
                    """
                INSERT INTO {}
                    (name, token, created_at, expires_at)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (token) DO UPDATE SET
                    name = EXCLUDED.name,
                    expires_at = EXCLUDED.expires_at
                """,
                ).format(_tokens_table()),
                (name, token_value, now, expires_at),
            )
        return token_value


def delete_token(token_id: int | None, token_value: str | None) -> bool:
    init_tokens_db()
    with postgres_connect() as conn:
        with conn.cursor() as cursor:
            if token_id is not None:
                cursor.execute(
                    sql.SQL("DELETE FROM {} WHERE id = %s").format(_tokens_table()),
                    (token_id,),
                )
            elif token_value:
                cursor.execute(
                    sql.SQL("DELETE FROM {} WHERE token = %s").format(
                        _tokens_table()
                    ),
                    (token_value,),
                )
            else:
                return False
            return cursor.rowcount > 0


def find_token(token: str) -> dict[str, Any] | None:
    init_tokens_db()
    with postgres_connect() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                sql.SQL(
                    """
                SELECT id, name, token, created_at, expires_at
                FROM {}
                WHERE token = %s
                """,
                ).format(_tokens_table()),
                (token,),
            )
            return cursor.fetchone()


def upsert_token_record(record: dict[str, Any]) -> None:
    init_tokens_db()
    with postgres_connect() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                sql.SQL(
                    """
                INSERT INTO {}
                    (id, name, token, created_at, expires_at)
                VALUES (%s, %s, %s, %s, %s)
                ON CONFLICT (token) DO UPDATE SET
                    name = EXCLUDED.name,
                    created_at = EXCLUDED.created_at,
                    expires_at = EXCLUDED.expires_at
                """,
                ).format(_tokens_table()),
                (
                    record.get("id"),
                    record.get("name"),
                    record.get("token"),
                    record.get("created_at"),
                    record.get("expires_at"),
                ),
            )

def is_valid_token(token: str) -> bool:
    record = find_token(token)
    if record is None:
        return False
    expires_at = int(record.get("expires_at") or 0)
    return expires_at == 0 or int(time.time()) < expires_at


def ensure_bootstrap_token(token: str | None) -> None:
    token_value = (token or "").strip()
    if token_value:
        insert_token("Agno AIOS Agent", 0, token_value)
